#!/bin/bash
services=("apache2" "mysql" "ssh")
for service in "${services[@]}"; do
    if systemctl is-acticve --quit "$service"; then
        echo "Service $service is running"
    else
        echo "Service $service is not running"
        # Restart service or send alert here
    fi
done
